### PR TITLE
Changes on the structure

### PR DESCRIPTION
**Pull request by dir-abood**

### CODE REVIEW

**Comment by dir-abood** [comment]
Hey. I really liked your script. I added some structuring. Let me know what you think.

**Review by V8gaming — COMMENTED** [review]
When I try a run it i get a type error "TypeError: 'type' object is not subscriptable" at line 22.
```
def entry_function() -> tuple[Path, str, float, Path, Path, Path]:
```

**Comment by dir-abood** [comment]
> When I try a run it i get a type error "TypeError: 'type' object is not subscriptable" at line 22.
> 
> ```
> def entry_function() -> tuple[Path, str, float, Path, Path, Path]:
> ```

Are you using python3.9? If not, you could do the following:
from typing import Tuple and then replace 'tuple' with Tuple.

**Comment by V8gaming** [comment]
That would make sense i'm using 3.7

**Comment by dir-abood** [comment]
Yeah python3.9 makes life easy in terms of type annotations :)

**Comment by V8gaming** [comment]
I changed to python 3.9. it works but in VS it has alot of error lines it could just be intelisense or something else; it doesn't recognize 'with' as a statement. I'll pull it.

**Comment by dir-abood** [comment]
"with" statement is a valid statement in newer versions of python. It helps remove writing close() after opening a file or image. The Image object has that capability.

**Pull request merged**
